name: hackkorea2022
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.21.0
  google_sign_in: 5.4.1
  firebase_auth: 3.6.4
  cloud_firestore: 3.4.5
  google_maps_flutter: 2.1.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

